local Config = require("lexicard_config")

describe("Config.parse", function()
    it("reads KEY=value lines and skips comments and blanks", function()
        local v = Config.parse("# comment\n\nGEMINI_API_KEY=abc\nANKI_DECK = Reading vocabulary \n")
        assert_eq(v.GEMINI_API_KEY, "abc")
        assert_eq(v.ANKI_DECK, "Reading vocabulary")
    end)
    it("strips matching quotes and keeps inner spaces", function()
        local v = Config.parse('A="hello world"\nB=\'x y\'')
        assert_eq(v.A, "hello world")
        assert_eq(v.B, "x y")
    end)
    it("drops inline comments on unquoted values", function()
        assert_eq(Config.parse("URLS=http://a:8765   # the Mac").URLS, "http://a:8765")
    end)
    it("handles Windows line endings", function()
        assert_eq(Config.parse("A=1\r\nB=2\r\n").B, "2")
    end)
end)

describe("Config.from_values", function()
    it("applies defaults", function()
        local cfg = Config.from_values({})
        assert_eq(cfg.gemini_model, "gemini-3.5-flash-lite")
        assert_eq(cfg.gemini_fallback_model, "gemini-3.6-flash")
        assert_eq(cfg.anki_deck, "Reading vocabulary")
        assert_eq(cfg.anki_note_type, "Lexicard")
        assert_eq(cfg.native_language, "Spanish (Mexico)")
        assert_eq(cfg.level, "B1-B2")
        assert_eq(cfg.tls_verify, true)
        assert_same(cfg.ankiconnect_urls, {})
    end)
    it("splits comma-separated URLs", function()
        local cfg = Config.from_values({ ANKICONNECT_URLS = "http://a:8765, http://b:8765" })
        assert_same(cfg.ankiconnect_urls, { "http://a:8765", "http://b:8765" })
    end)
    it("lets TLS_VERIFY=false turn verification off", function()
        assert_eq(Config.from_values({ TLS_VERIFY = "false" }).tls_verify, false)
    end)
    it("ignores empty values", function()
        assert_eq(Config.from_values({ ANKI_DECK = "" }).anki_deck, "Reading vocabulary")
    end)
end)

describe("Config.missing and Config.load", function()
    it("reports missing required keys", function()
        assert_same(Config.missing(Config.from_values({})), { "GEMINI_API_KEY", "ANKICONNECT_URLS" })
    end)
    it("returns defaults and false when the file does not exist", function()
        local cfg, found = Config.load("/nonexistent/lexicard.env")
        assert_eq(found, false)
        assert_eq(cfg.anki_deck, "Reading vocabulary")
    end)
    it("loads a file", function()
        local path = os.tmpname()
        local f = assert(io.open(path, "w"))
        f:write("GEMINI_API_KEY=k\nANKICONNECT_URLS=http://x:8765\n")
        f:close()
        local cfg, found = Config.load(path)
        os.remove(path)
        assert_eq(found, true)
        assert_eq(cfg.gemini_api_key, "k")
        assert_same(Config.missing(cfg), {})
    end)
end)
