local Ipa = require("lexicard_ipa")

local function write(lines)
    local path = os.tmpname()
    local f = assert(io.open(path, "w"))
    f:write(table.concat(lines, "\n"), "\n")
    f:close()
    return path
end

local SMALL = { "bank\tbæŋk", "give\tɡɪv", "read\trɛd|rid", "up\tʌp" }

describe("Ipa.lookup", function()
    it("finds words in a small sorted file", function()
        local path = write(SMALL)
        assert_same(Ipa.lookup(path, "give"), { "ɡɪv" })
        assert_same(Ipa.lookup(path, "read"), { "rɛd", "rid" })
        assert_eq(Ipa.lookup(path, "zebra"), nil)
        assert_eq(Ipa.lookup(path, "aardvark"), nil)
        os.remove(path)
    end)
    it("finds every probed word in a large file", function()
        local lines = {}
        for i = 1, 20000 do lines[i] = ("w%05d\tipa%d"):format(i, i) end
        local path = write(lines)
        for _, i in ipairs({ 1, 2, 777, 10000, 19999, 20000 }) do
            assert_same(Ipa.lookup(path, ("w%05d"):format(i)), { "ipa" .. i })
        end
        assert_eq(Ipa.lookup(path, "w20001"), nil)
        os.remove(path)
    end)
    it("returns nil when the file is missing", function()
        assert_eq(Ipa.lookup("/nonexistent/cmudict-ipa.tsv", "give"), nil)
    end)
end)

describe("Ipa.for_headword", function()
    it("joins unambiguous words and refuses ambiguous or unknown ones", function()
        local path = write(SMALL)
        assert_eq(Ipa.for_headword(path, "give up"), "/ɡɪv ʌp/")
        assert_eq(Ipa.for_headword(path, "Bank"), "/bæŋk/")
        assert_eq(Ipa.for_headword(path, "read"), nil)
        assert_eq(Ipa.for_headword(path, "give in"), nil)
        os.remove(path)
    end)
    it("picks the variant closest to the model's guess", function()
        local path = write(SMALL)
        assert_eq(Ipa.for_headword(path, "read", "/riːd/"), "/rid/")
        assert_eq(Ipa.for_headword(path, "read", "/ˈɹɛd/"), "/rɛd/")
        assert_eq(Ipa.for_headword(path, "read up", "/riːd ʌp/"), "/rid ʌp/")
        os.remove(path)
    end)
    it("treats ɚ and ər as the same sound when comparing", function()
        local path = write({ "record\trəˈkɔrd|ˈrɛkɚd|rɪˈkɔrd" })
        assert_eq(Ipa.for_headword(path, "record", "/ˈrɛkərd/"), "/ˈrɛkɚd/")
        assert_eq(Ipa.for_headword(path, "record", "/rɪˈkɔːrd/"), "/rɪˈkɔrd/")
        os.remove(path)
    end)
    it("replaces a garbage guess with dictionary pronunciations", function()
        local path = write({ "cake\tkeɪk", "of\tʌv|əv", "piece\tpis" })
        assert_eq(Ipa.for_headword(path, "piece of cake", "/opak/"), "/pis ʌv keɪk/")
        os.remove(path)
    end)
end)

describe("Ipa.distance", function()
    it("counts edits between UTF-8 strings", function()
        assert_eq(Ipa.distance("rɛd", "rɛd"), 0)
        assert_eq(Ipa.distance("rɛd", "rid"), 1)
        assert_eq(Ipa.distance("", "ʌv"), 2)
    end)
end)

describe("Ipa v2", function()
    it("normalizes model IPA to Oxford American style", function()
        assert_eq(Ipa.style("/ˈbɜːrd/"), "/ˈbərd/")
        assert_eq(Ipa.style("/ɡɪv ʌp/"), "/ɡɪv ʌp/")
        assert_eq(Ipa.style("/'riː.ə.laɪz/"), "/ˈriəlaɪz/")
        assert_eq(Ipa.style("/ˈtiːtʃɚ/"), "/ˈtitʃər/")
    end)
    it("accepts plausible model IPA and rejects garbage", function()
        assert_eq(Ipa.check_model("/ɡɪv ʌp/", "give up"), "/ɡɪv ʌp/")
        assert_eq(Ipa.check_model("/opak/", "piece of cake"), nil)
        assert_eq(Ipa.check_model("/x1/", "x"), nil)
        assert_eq(Ipa.check_model("", "word"), nil)
    end)
    it("stresses the particle of a phrasal verb", function()
        assert_same(Ipa.phrasal_stress({ "ɡɪv", "ʌp" }), { "ˌɡɪv", "ˈʌp" })
        assert_same(Ipa.phrasal_stress({ "ˈkæri", "ɑn" }), { "ˌkæri", "ˈɑn" })
        assert_same(Ipa.phrasal_stress({ "pʊt", "ʌp", "wɪð" }), { "ˌpʊt", "ˈʌp", "wɪð" })
    end)
    it("picks dictionary IPA, then plausible model IPA, else nothing", function()
        local path = write({ "give\tɡɪv", "up\tʌp" })
        assert_eq(Ipa.for_card(path, { headword = "give up", pos = "phrasal verb", ipa = "" }), "/ˌɡɪv ˈʌp/")
        assert_eq(Ipa.for_card(path, { headword = "give up", pos = "verb", ipa = "" }), "/ɡɪv ʌp/")
        assert_eq(Ipa.for_card(path, { headword = "allomancy", pos = "noun", ipa = "/əˈlɑmənsi/" }), "/əˈlɑmənsi/")
        assert_eq(Ipa.for_card(path, { headword = "piece of cake", pos = "idiom", ipa = "/opak/" }), "")
        os.remove(path)
    end)
end)
