local Json = require("lexicard_json")

describe("lexicard_json", function()
    it("quotes strings with escapes", function()
        assert_eq(Json.quote('a "b"\n\\ ⟦c⟧'), '"a \\"b\\"\\n\\\\ ⟦c⟧"')
    end)
    it("escapes other control characters as \\u", function()
        assert_eq(Json.quote("\1"), '"\\u0001"')
    end)
    it("round-trips a quoted string through decode", function()
        local s = 'Mix: "quotes", \\ backslash, tab\t, ñ, ⟦x⟧'
        assert_eq(Json.decode('{"v":' .. Json.quote(s) .. '}').v, s)
    end)
    it("encodes empty arrays as []", function()
        assert_eq(Json.encode(Json.array({})), "[]")
    end)
    it("returns nil and an error for invalid JSON", function()
        local value, err = Json.decode("{not json")
        assert_eq(value, nil)
        assert_true(err ~= nil)
    end)
    it("recognizes JSON null", function()
        assert_true(Json.is_null(Json.decode('{"error": null}').error))
    end)
end)
