local Picture = require("lexicard_picture")
local Config = require("lexicard_config")
local Json = require("lexicard_json")

local cfg = Config.from_values({ CLOUDFLARE_ACCOUNT_ID = "acc", CLOUDFLARE_API_TOKEN = "tok" })

describe("Picture", function()
    it("builds the prompt from the scene plus the deck style", function()
        assert_eq(Picture.prompt({ picture_scene = "" }), nil)
        assert_eq(Picture.prompt({ picture_scene = "A leaf." }), "A leaf. " .. Picture.STYLE)
    end)
    it("writes a multipart body", function()
        local body, ctype = Picture.multipart({ { "prompt", "a b" }, { "width", "1024" } }, "XYZ")
        assert_eq(ctype, "multipart/form-data; boundary=XYZ")
        assert_eq(body, '--XYZ\r\nContent-Disposition: form-data; name="prompt"\r\n\r\na b\r\n'
            .. '--XYZ\r\nContent-Disposition: form-data; name="width"\r\n\r\n1024\r\n--XYZ--\r\n')
    end)
    it("asks Cloudflare for a 1024×768 picture and returns the base64 JPEG", function()
        local seen
        local image = Picture.draw(cfg, "A leaf.", function(request)
            seen = request
            return 200, Json.encode({ result = { image = "/9j/AAAA" }, success = true })
        end)
        assert_eq(image, "/9j/AAAA")
        assert_eq(seen.method, "POST")
        assert_eq(seen.url, "https://api.cloudflare.com/client/v4/accounts/acc/ai/run/@cf/black-forest-labs/flux-2-klein-4b")
        assert_eq(seen.headers.Authorization, "Bearer tok")
        assert_match(seen.headers["Content-Type"], "^multipart/form%-data; boundary=")
        assert_match(seen.body, 'name="prompt"\r\n\r\nA leaf%.\r\n')
        assert_match(seen.body, 'name="width"\r\n\r\n1024\r\n')
        assert_match(seen.body, 'name="height"\r\n\r\n768\r\n')
    end)
    it("explains failures", function()
        local function code(c) return function() return c, "{}" end end
        assert_same({ Picture.draw(cfg, "x", code(401)) }, { nil, "check the Cloudflare token" })
        assert_same({ Picture.draw(cfg, "x", code(429)) }, { nil, "daily picture limit reached" })
        assert_same({ Picture.draw(cfg, "x", code(500)) }, { nil, "Cloudflare HTTP 500" })
        assert_same({ Picture.draw(cfg, "x", function() return nil, "timeout" end) }, { nil, "network error" })
        assert_same({ Picture.draw(cfg, "x", code(200)) }, { nil, "no picture in reply" })
        assert_same({ Picture.draw(cfg, nil, code(200)) }, { nil, "nothing to draw" })
    end)
    it("checks the token without drawing", function()
        local seen
        local result = Picture.check(cfg, function(request)
            seen = request
            return 200, Json.encode({ success = true, result = { status = "active" } })
        end)
        assert_eq(result.ok, true)
        assert_eq(seen.url, "https://api.cloudflare.com/client/v4/user/tokens/verify")
        assert_eq(Picture.check(Config.from_values({}), function() error("no call") end).ok, false)
    end)
end)
