local Text = require("lexicard_text")

describe("Text.fold and words", function()
    it("lowercases and removes Spanish accents", function()
        assert_eq(Text.fold("  Éxito Rápido Ñandú "), "exito rapido nandu")
    end)
    it("splits words and ignores tags, marks and punctuation", function()
        assert_same(Text.words("He <b>gave</b> it ⟦up⟧, didn't he?"), { "he", "gave", "it", "up", "didn't", "he" })
    end)
    it("keeps content words only", function()
        assert_same(Text.content_words("give sth up"), { "give" })
        assert_same(Text.content_words("a piece of cake"), { "piece", "cake" })
    end)
end)

describe("Text.same_family and mentions", function()
    it("matches forms of long words by stem", function()
        assert_true(Text.same_family("reluctantly", "reluctant"))
        assert_true(Text.same_family("embarrassing", "embarrassed"))
        assert_true(not Text.same_family("real", "realize"))
    end)
    it("matches short words only with real suffixes", function()
        assert_true(Text.same_family("gives", "give"))
        assert_true(Text.same_family("running", "run"))
        assert_true(not Text.same_family("little", "lit"))
    end)
    it("finds the headword family in a definition", function()
        assert_true(Text.mentions("to give something up", "give up"))
        assert_true(not Text.mentions("to stop doing something", "give up"))
    end)
end)

describe("Text.overlap", function()
    it("measures how much of an example repeats the book", function()
        assert_eq(Text.overlap("She gave it up after years.", "She gave it up after years."), 1)
        assert_true(Text.overlap("I gave up coffee last month.", "She tried the violin for years.") < 0.5)
    end)
end)

describe("Text.looks_alike and distance", function()
    it("recognizes Spanish look-alikes of English words", function()
        assert_true(Text.looks_alike("realizar", "realize"))
        assert_true(Text.looks_alike("simpático", "sympathetic"))
        assert_true(Text.looks_alike("soportar", "support"))
        assert_true(Text.looks_alike("éxito", "exit"))
        assert_true(not Text.looks_alike("darse", "realize"))
    end)
    it("counts edits in characters", function()
        assert_eq(Text.distance("rɛd", "rid"), 1)
        assert_eq(Text.distance("", "ʌv"), 2)
    end)
end)

describe("Text.overlap with an ignored headword", function()
    it("counts only the words around the expression", function()
        assert_eq(Text.overlap("The test was a piece of cake.", "The exam was a piece of cake.", "piece of cake"), 0)
        assert_eq(Text.overlap("Can I borrow a pen?", "Can I borrow your pen for a minute?", "borrow"), 1)
        assert_eq(Text.overlap("Lit!", "That party was lit.", "lit"), 0)
    end)
end)
