local Traps = require("lexicard_traps")

describe("Traps", function()
    it("knows common false friends", function()
        assert_same(Traps.false_friend("Realize"), { lookalike = "realizar", say = "darse cuenta" })
        assert_eq(Traps.false_friend("walk"), nil)
    end)
    it("writes a ✗/✓ warning for a known false friend", function()
        assert_eq(Traps.false_friend_warning("actually"), "Falso amigo: ✗ «actualmente» → ✓ «en realidad»")
    end)
    it("builds the reference lists for the prompt", function()
        local text = Traps.prompt_lists()
        assert_match(text, "actually ≠ actualmente → en realidad")
        assert_match(text, "%*depend of → depend on")
        assert_true(not text:find("ed_ending", 1, true))
    end)
    it("lists prepositions and vulgar words in folded form", function()
        assert_true(Traps.PREPOSITIONS.on)
        assert_true(Traps.VULGAR.chingon)
    end)
end)

describe("Traps.confusable", function()
    it("explains English pairs that share one Spanish verb", function()
        assert_eq(Traps.confusable_warning("borrow"), "En español ambos son «prestar»: borrow = pedir prestado; lend = prestar a alguien")
        assert_eq(Traps.confusable_warning("walk"), nil)
    end)
    it("lists the pairs in the prompt", function()
        assert_match(Traps.prompt_lists(), "borrow/lend %(prestar%)")
    end)
end)

describe("Traps.confusable autofill", function()
    it("leaves words with several meanings to the model", function()
        assert_eq(Traps.confusable_warning("miss"), nil)
        assert_eq(Traps.confusable_warning("take"), nil)
        assert_match(Traps.prompt_lists(), "miss/lose %(perder%)")
    end)
end)
