local Traps = require("lexicard_traps")

describe("Traps", function()
    it("knows common false friends", function()
        assert_same(Traps.false_friend("Realize"), { lookalike = "realizar", say = "darse cuenta" })
        assert_eq(Traps.false_friend("walk"), nil)
    end)
    it("writes a ✗/✓ warning for a known false friend", function()
        assert_eq(Traps.false_friend_warning("actually"), "Falso amigo: ✗ «actualmente» → ✓ «en realidad»")
    end)
    it("builds the reference lists for the prompt", function()
        local text = Traps.prompt_lists()
        assert_match(text, "actually ≠ actualmente → en realidad")
        assert_match(text, "%*depend of → depend on")
        assert_match(text, "ed_ending: ")
    end)
    it("lists prepositions and vulgar words in folded form", function()
        assert_true(Traps.PREPOSITIONS.on)
        assert_true(Traps.VULGAR.chingon)
    end)
end)
